name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y gcc g++

    - name: Compile C files
      run: |
        gcc -Wall -Wextra -Werror -o main *.c
        # Optionally, add -fsanitize=address for memory checks (debug builds)

    - name: Run program
      run: |
        ./main
        # Optional: Add test cases here (e.g., check expected output)
        # Example: ./main <<< "5" | grep "Fibonacci is 5" || exit 1

    # Optional: Add a step to run tests (if you have a test suite)
    # - name: Run tests
    #   run: |
    #     ./run_tests.sh
